export const QUIZ_LIST_REQUEST = "QUIZ_LIST_REQUEST";
export const QUIZ_LIST_FAIL = "QUIZ_LIST_FAIL";
export const QUIZ_LIST_SUCCESS = "QUIZ_LIST_SUCCESS";

export const MYQUIZ_LIST_REQUEST = "MYQUIZ_LIST_REQUEST";
export const MYQUIZ_LIST_FAIL = "MYQUIZ_LIST_FAIL";
export const MYQUIZ_LIST_SUCCESS = "MYQUIZ_LIST_SUCCESS";

export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";

export const QUIZ_CREATE_REQUEST = "QUIZ_CREATE_REQUEST";
export const QUIZ_CREATE_FAIL = "QUIZ_CREATE_FAIL";
export const QUIZ_CREATE_SUCCESS = "QUIZ_CREATE_SUCCESS";

export const QUIZ_DELETE_REQUEST = "QUIZ_DELETE_REQUEST";
export const QUIZ_DELETE_FAIL = "QUIZ_DELETE_FAIL";
export const QUIZ_DELETE_SUCCESS = "QUIZ_DELETE_SUCCESS";

export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_FAIL = "QUESTION_CREATE_FAIL";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CLEAR = "QUESTION_CLEAR";

export const GENERATE_REPORT_REQUEST = "GENERATE_REPORT_REQUEST";
export const GENERATE_REPORT_FAIL = "GENERATE_REPORT_FAIL";
export const GENERATE_REPORT_SUCCESS = "GENERATE_REPORT_SUCCESS ";
