export const QUIZ_LIST_REQUEST = "QUIZ_LIST_REQUEST";
export const QUIZ_LIST_FAIL = "QUIZ_LIST_FAIL";
export const QUIZ_LIST_SUCCESS = "QUIZ_LIST_SUCCESS";

export const MYQUIZ_LIST_REQUEST = "MYQUIZ_LIST_REQUEST";
export const MYQUIZ_LIST_FAIL = "MYQUIZ_LIST_FAIL";
export const MYQUIZ_LIST_SUCCESS = "MYQUIZ_LIST_SUCCESS";

export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";

export const QUIZ_CREATE_REQUEST = "QUIZ_CREATE_REQUEST";
export const QUIZ_CREATE_FAIL = "QUIZ_CREATE_FAIL";
export const QUIZ_CREATE_SUCCESS = "QUIZ_CREATE_SUCCESS";

export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_FAIL = "QUESTION_CREATE_FAIL";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CLEAR = "QUESTION_CLEAR";
