export const QUIZ_RESPONSE_CREATE_REQUEST = "QUIZ_RESPONSE_CREATE_REQUEST";
export const QUIZ_RESPONSE_CREATE_FAIL = "QUIZ_RESPONSE_CREATE_FAIL";
export const QUIZ_RESPONSE_CREATE_SUCCESS = "QUIZ_RESPONSE_CREATE_SUCCESS";
